name: 'Add a changeset for dependency updates'
description: ''
author: 'Matthew Scharley'

# Define your inputs here.
inputs:
  changeset-folder:
    description: 'Which folder to store your changesets in'
    required: false
    default: '.changeset'
  token:
    description: 'A Github access token used to push commits back to the PR'
    required: true

# Define your outputs here.
outputs:
  created-changeset:
    description: 'Whether a new changeset was created or not'

runs:
  using: node20
  main: dist/index.js
